export const UPDATE_CONTACTS_REQS = 'UPDATE_CONTACTS_REQS';
export const UPDATE_CONTACTS_FAILED = 'UPDATE_CONTACTS_FAILED';
export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS';
export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';